/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tictactoegame;

import javax.swing.JOptionPane;

/**
 *
 * @author Surachai
 */
public class gameJFrame extends javax.swing.JFrame {

    int turn = 2;
    int buttonUsed[] = {0,0,0,0,0,0,0,0,0};
    int Xwon[] = {0,0,0,0,0,0,0,0,0};
    int Owon[] = {0,0,0,0,0,0,0,0,0};
    
    int Xwon(){
        if(Xwon[0] == 1 && Xwon[1] == 1 && Xwon[2] == 1){
            return 1;
        }
        if(Xwon[3] == 1 && Xwon[4] == 1 && Xwon[5] == 1){
            return 1;
        }
        if(Xwon[6] == 1 && Xwon[7] == 1 && Xwon[8] == 1){
            return 1;
        }
        if(Xwon[0] == 1 && Xwon[3] == 1 && Xwon[6] == 1){
            return 1;
        }
        if(Xwon[1] == 1 && Xwon[4] == 1 && Xwon[7] == 1){
            return 1;
        }
        if(Xwon[2] == 1 && Xwon[5] == 1 && Xwon[8] == 1){
            return 1;
        }
        if(Xwon[0] == 1 && Xwon[4] == 1 && Xwon[8] == 1){
            return 1;
        }
        if(Xwon[2] == 1 && Xwon[4] == 1 && Xwon[6] == 1){
            return 1;
        }
        return 0;
    }
    
    int Owon(){
        if(Owon[0] == 1 && Owon[1] == 1 && Owon[2] == 1){
            return 1;
        }
        if(Owon[3] == 1 && Owon[4] == 1 && Owon[5] == 1){
            return 1;
        }
        if(Owon[6] == 1 && Owon[7] == 1 && Owon[8] == 1){
            return 1;
        }
        if(Owon[0] == 1 && Owon[3] == 1 && Owon[6] == 1){
            return 1;
        }
        if(Owon[1] == 1 && Owon[4] == 1 && Owon[7] == 1){
            return 1;
        }
        if(Owon[2] == 1 && Owon[5] == 1 && Owon[8] == 1){
            return 1;
        }
        if(Owon[0] == 1 && Owon[4] == 1 && Owon[8] == 1){
            return 1;
        }
        if(Owon[2] == 1 && Owon[4] == 1 && Owon[6] == 1){
            return 1;
        }
        return 0;
    }
    
    public gameJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box5 = new javax.swing.JButton();
        box4 = new javax.swing.JButton();
        box6 = new javax.swing.JButton();
        box8 = new javax.swing.JButton();
        box7 = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        box0 = new javax.swing.JButton();
        box2 = new javax.swing.JButton();
        box1 = new javax.swing.JButton();
        box3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        box5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        box6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });

        box8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });

        box7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });

        resetbtn.setText("PLAY AGAIN");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        box0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box0ActionPerformed(evt);
            }
        });

        box2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(box7, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(box0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(box1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(box5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box0, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box4, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(box3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(box8, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(box7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(box6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
       if(buttonUsed[5] == 0){
            if(turn % 2 == 0){
                turn++;
                box5.setText("X");
                buttonUsed[5] = 1;
                Xwon[5] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box5.setText("O");
                buttonUsed[5] = 1;
                Owon[5] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }
    }//GEN-LAST:event_box5ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        if(buttonUsed[4] == 0){
            if(turn % 2 == 0){
                turn++;
                box4.setText("X");
                buttonUsed[4] = 1;
                Xwon[4] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box4.setText("O");
                buttonUsed[4] = 1;
                Owon[4] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }
    }//GEN-LAST:event_box4ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        if(buttonUsed[6] == 0){
            if(turn % 2 == 0){
                turn++;
                box6.setText("X");
                buttonUsed[6] = 1;
                Xwon[6] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box6.setText("O");
                buttonUsed[6] = 1;
                Owon[6] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }
    }//GEN-LAST:event_box6ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
     if(buttonUsed[8] == 0){
            if(turn % 2 == 0){
                turn++;
                box8.setText("X");
                buttonUsed[8] = 1;
                Xwon[8] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box8.setText("O");
                buttonUsed[8] = 1;
                Owon[8] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }  
    }//GEN-LAST:event_box8ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
     if(buttonUsed[7] == 0){
            if(turn % 2 == 0){
                turn++;
                box7.setText("X");
                buttonUsed[7] = 1;
                Xwon[7] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box7.setText("O");
                buttonUsed[7] = 1;
                Owon[7] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }  
    }//GEN-LAST:event_box7ActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        box0.setText("");
        box1.setText("");
        box2.setText("");
        box3.setText("");
        box4.setText("");
        box5.setText("");
        box6.setText("");
        box7.setText("");
        box8.setText("");

        turn = 2;
        for(int i = 0; i < 9; i++){
            buttonUsed[i] = 0;
            Xwon[i] = 0;
            Owon[i] = 0;
        }
    }//GEN-LAST:event_resetbtnActionPerformed

    private void box0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box0ActionPerformed
        if(buttonUsed[0] == 0){
            if(turn % 2 == 0){
                turn++;
                box0.setText("X");
                buttonUsed[0] = 1;
                Xwon[0] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box0.setText("O");
                buttonUsed[0] = 1;
                Owon[0] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }
    }//GEN-LAST:event_box0ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        if(buttonUsed[2] == 0){
            if(turn % 2 == 0){
                turn++;
                box2.setText("X");
                buttonUsed[2] = 1;
                Xwon[2] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box2.setText("O");
                buttonUsed[2] = 1;
                Owon[2] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }
    }//GEN-LAST:event_box2ActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
       if(buttonUsed[1] == 0){
            if(turn % 2 == 0){
                turn++;
                box1.setText("X");
                buttonUsed[1] = 1;
                Xwon[1] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box1.setText("O");
                buttonUsed[1] = 1;
                Owon[1] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }
    }//GEN-LAST:event_box1ActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
       if(buttonUsed[3] == 0){
            if(turn % 2 == 0){
                turn++;
                box3.setText("X");
                buttonUsed[3] = 1;
                Xwon[3] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }else{
                turn++;
                box3.setText("O");
                buttonUsed[3] = 1;
                Owon[3] = 1;

                int Xresult = Xwon();
                int Oresult = Owon();

                if(Xresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player X won");
                }else if(Oresult == 1){
                    JOptionPane.showMessageDialog(rootPane,"Player O won");
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"THIS BUTTON IS ALREADY USED");
        }
    }//GEN-LAST:event_box3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton box0;
    private javax.swing.JButton box1;
    private javax.swing.JButton box2;
    private javax.swing.JButton box3;
    private javax.swing.JButton box4;
    private javax.swing.JButton box5;
    private javax.swing.JButton box6;
    private javax.swing.JButton box7;
    private javax.swing.JButton box8;
    private javax.swing.JButton resetbtn;
    // End of variables declaration//GEN-END:variables
}
